# Generated by Django 4.1.7 on 2023-04-23 16:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='recipe_avatars/no-photo.png', null=True, upload_to='recipe_avatars/')),
                ('amounts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('total_proteins', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('total_carbohydrates', models.FloatField()),
                ('total_calories', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='app.product')),
                ('steps', models.ManyToManyField(to='app.step')),
            ],
        ),
    ]
