# Generated by Django 4.1.7 on 2023-04-29 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
