# Generated by Django 4.1.7 on 2023-05-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFree',
            field=models.BooleanField(default=True),
        ),
    ]
